source 'https://rubygems.org'
gem 'chef-zero'
gem  'hipchat'
gem 'collins_shell'
gem 'dnsmadeeasy-api'
gem 'foodcritic'
gem 'knife-block', '~> 0.0'
gem 'tailor'
gem 'hipchat'
gem 'rubocop'
gem 'knife-spork'
gem 'guard'
gem 'guard-kitchen'
gem 'guard-foodcritic', '>= 1.0'
gem 'guard-rspec', '>= 4.2'
gem 'guard-rubocop'

