source 'https://rubygems.org'
gem 'chef-zero'
#gem 'collins_shell'
gem 'dnsmadeeasy-api'
gem 'foodcritic'
gem 'knife-block'
gem 'tailor'
gem 'hipchat'
gem 'rubocop'
gem 'knife-spork'
gem 'knife-lastrun'

