version_change_threshold: 2
preserve_constraint_operators: true
environment_path: "/Users/silviabotros/Documents/git/chef-data/environments"
save_environment_locally_on_create: false
role_path: "/Users/silviabotros/Documents/git/chef-data/roles"
custom_plugin_path: "/Users/silviabotros/spork-plugins"
always_promote_remote: true
skip_berkshelf: false
role_match_file_name: true
json_options:
  indent: "    "
plugins:
  foodcritic:
    tags: ['any']
  hipchat:
    api_token: 6d883f8f9f30c24f781f6f01597de2
    rooms:
      - Prod Handoff
      - @Handoff
    notify: true
    color: yellow
  git:
    enabled: true
    auto_push: true
  graphite:
    server: graphite.sendgrid.net
    port: 2003
#  rubocop:
#    epic_fail: true
#    show_name: false
#    autocorrect: false
#    out_file: <file>
#    sev_level: <C|W|E>
#    lint: false
